version: '3'

services:
    nginx:
      image: ${NGINX_IMAGE_BASE}:${NGINX_IMAGE_TAG}
      ports:
        - "${NGINX_HTTP_PORT}:80"
        - "${NGINX_HTTPS_PORT}:443"
        - "${NGINX_HTTP_PORT_72}:8072"
      volumes:
        - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf
        - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
        - ${NGINX_LOG_DIR}:/var/log/nginx
        - ${SOURCE_SHARE_DIR}:/var/www
        - ${NGINX_SSL_DIR}:/etc/letsencrypt
      restart: always
      environment:
          TZ: Asia/Shanghai  
      container_name: dnmp-nginx
      networks:
          - backend
    php72:
      build:
        context: .
        args:
          PHP_VERSION: ${PHP72_VERSION}
          ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
          PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
          MORE_EXTENSION_INSTALLER: php72.sh
      #image: ${PHP_IMAGE_BASE}:${PHP72_IMAGE_TAG}
      ports:
        - "${PHP72_FPM_PORT}:9000"
        - "${PHP72_WORKERMAN_PORT}:9502"
      volumes:
        - ${SOURCE_SHARE_DIR}:/var/www
        - ${PHP_INI_FILE}:/usr/local/php/etc/php.ini
        - ${PHP_FPM_CONF_FILE}:/usr/local/php/etc/php-fpm.conf
        - ${PHP_WWW_CONF_FILE}:/usr/local/php/etc/php-fpm.d/www.conf
      networks:
        - backend    
      container_name: ${PHP72_CONTAINER_NAME}
    php56:
      build:
        context: .
        args:
          PHP_VERSION: ${PHP56_VERSION}
          ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
          PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
          MORE_EXTENSION_INSTALLER: php72.sh
      #image: ${PHP_IMAGE_BASE}:${PHP56_IMAGE_TAG}
      ports:
        - "${PHP56_FPM_PORT}:9000"
      volumes:
        - ${SOURCE_SHARE_DIR}:/var/www
        - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini
        - ${PHP_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
        - ${NGINX_LOG_DIR}:/var/log/php
      networks:
        - backend
      container_name: ${PHP56_CONTAINER_NAME}
    mysql:
      image: mysql:${MYSQL_IMAGE_TAG}
      restart: always
      command: --default-authentication-plugin=mysql_native_password 
      hostname: dnmp-mysql
      ports:
        - "3308:3306"
      volumes:
        - ${MYSQL_DATA_DIR}:/var/lib/mysql
        - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
      environment:
          MYSQL_ROOT_PASSWORD: 123456  
      networks:
        - backend
      restart: always
      container_name: dnmp-mysql
    redis:
      image: redis:${REDIS_IMAGE_TAG}
      hostname: dnmp-redis
      ports:
        - "${REDIS_HOST_PORT}:6379"
      command: redis-server /usr/local/etc/redis/redis.conf    
      networks:
        - backend      
      volumes:
        - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
        - ${REDIS_DATA_DIR}:/data
      restart: always
      container_name: dnmp-redis
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:${PHPMYADMIN_TAG}
      ports:
        - "${PHPMYADMIN_HOST_PORT}:80"
      networks:
        - backend
      environment:
        - PMA_HOST=dnmp-mysql
        - PMA_PORT=3306
      container_name: dnmp-phpmyadmin    
networks:
  backend:
    driver: bridge   
