version: '3'

services:
    nginx:
        depends_on:
            - php
        image: nginx:1.14.2-alpine
        ports:
            - 80:80
            - 443:443
        volumes:
           - ./conf/nginx.conf:/etc/nginx/nginx.conf
           - ./conf/conf.d:/etc/nginx/conf.d
           - ./log:/var/log/nginx
           - ./www:/var/www
           - ./etc/letsencrypt:/etc/letsencrypt
        restart: always
        environment:
           TZ: Asia/Shanghai  
        container_name: dnmp-nginx
        networks:
            - backend
    php:
        depends_on:
            - mysql
            - redis
        image: registry.cn-beijing.aliyuncs.com/tinywan/dnmp:php7.2-v4
        ports:
            - "9000:9000"
            - "9502:9502" # WorkerMan 端口
        volumes:
            - ./www:/var/www
            - ./etc/php.ini:/usr/local/php/etc/php.ini
            - ./etc/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
            - ./etc/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        networks:
            - backend    
        container_name: dnmp-php # 容器名称   
    mysql:
        image: mysql:5.7
        restart: always
        command: --default-authentication-plugin=mysql_native_password 
        hostname: dnmp-mysql
        ports:
            - "3308:3306"
        volumes:
            - ./etc/mysql/data:/var/lib/mysql
            - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: 123456  
        networks:
            - backend
        restart: always
        container_name: dnmp-mysql
    redis:
        image: redis:5.0-alpine
        hostname: dnmp-redis
        ports:
            - "63789:6379"
        command: redis-server /usr/local/etc/redis/redis.conf    
        networks:
            - backend      
        volumes:
            - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./etc/redis/data:/data
        restart: always
        container_name: dnmp-redis
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8082:80"
        networks:
            - backend
        environment:
            - PMA_HOST=dnmp-mysql
            - PMA_PORT=3306
        container_name: dnmp-phpmyadmin    
networks:
  backend:
    driver: bridge   
