version: '3'

services:
    lnmp-openresty:
        image: openresty/openresty:alpine
        ports:
          - 8880:80
          - 8881:81
        volumes:
          - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
          - ./conf/conf.d:/etc/nginx/conf.d
          - ./conf/lua:/usr/local/openresty/nginx/conf/lua
          - ./log:/var/log/nginx
          - ./www:/var/www
        container_name: dnmp-openresty-vv1
        networks:
          - backend
    php:
        image: registry.cn-beijing.aliyuncs.com/tinywan/dnmp:php7.2-v4
        ports:
            - "9000:9000"
        volumes:
            - ./www:/var/www
            - ./etc/php.ini:/usr/local/php/etc/php.ini
            - ./etc/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
            - ./etc/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        networks:
            - backend    
        container_name: dnmp-php-vv1 # 容器名称   
networks:
  backend:
    driver: bridge   