version: "3"

services:
    openresty:
        image: ${NGINX_IMAGE_BASE}:${NGINX_IMAGE_TAG}
        depends_on: 
          - php72
        ports:
          - "${NGINX_HTTP_PORT}:80"
          - "${NGINX_HTTPS_PORT}:443"
          - "8881:81"
        volumes:
          - ${NGINX_CONF_FILE}:/usr/local/openresty/nginx/conf/nginx.conf
          - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d
          - ${NGINX_LOG_DIR}:/var/log/nginx
          - ${SOURCE_SHARE_DIR}:/var/www
          - ${NGINX_LUA_DIR}:/usr/local/openresty/nginx/conf/lua
          - ${NGINX_SSL_DIR}:/etc/letsencrypt
        restart: always
        container_name: ${NGINX_CONTAINER_NAME}
        networks:
          - default
    php72:
        image: ${PHP_IMAGE_BASE}:${PHP72_IMAGE_TAG}
        depends_on:
          - redis
        ports:
          - "9009:9000"
        volumes:
          - ${SOURCE_SHARE_DIR}:/var/www
          - ${PHP_INI_FILE}:/usr/local/php/etc/php.ini
          - ${PHP_FPM_CONF_FILE}:/usr/local/php/etc/php-fpm.conf
          - ${PHP_WWW_CONF_FILE}:/usr/local/php/etc/php-fpm.d/www.conf
        container_name: ${PHP72_CONTAINER_NAME}   
        networks:
          - default    
    mysql:
        image: mysql:${MYSQL_IMAGE_TAG}
        restart: always
        command: --default-authentication-plugin=mysql_native_password 
        hostname: dnmp-mysql-v1
        ports:
            - "${MYSQL_HOST_PORT}:3306"
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: 123456  
        networks:
          - default
        restart: always
        container_name: dnmp-mysql-v2
    redis:
        image: redis:${REDIS_IMAGE_TAG}
        hostname: dnmp-redis-v1
        ports:
          - "${REDIS_HOST_PORT}:6379"
        command: redis-server /usr/local/etc/redis/redis.conf    
        volumes:
          - ${REDIS_CONF_FILE}:/usr/local/etc/redis/redis.conf
          - ${REDIS_DATA_DIR}:/data
        restart: always
        container_name: dnmp-redis-v2   
        networks:
          - default      
networks:
  default: